</br>
https://github.com/CesarC27</br>
https://github.com/FernandoHerreroGarcia</br>
https://github.com/MarioPerezRodriguez</br>
https://github.com/MiguelCalderonPuertas</br>
https://github.com/JesusPereez7</br>
https://github.com/Caampo03/smr2b_David</br>
</br>
https://github.com/dblancoformacion</br>